CREATE TABLE LoginEntity (
	LoginId INT IDENTITY(1, 1) PRIMARY KEY,
	Username VARCHAR(30) UNIQUE NOT NULL,
	Email VARCHAR(60) UNIQUE NOT NULL,
	Passwordi VARCHAR(512) NOT NULL,
);

--ALTER TABLE LoginEntity ALTER COLUMN Passwordi VARCHAR(512);

CREATE TABLE Useri (
	UserId INT IDENTITY(1, 1) PRIMARY KEY,
	Emri VARCHAR(30) NOT NULL,
	Mbiemri VARCHAR(30) NOT NULL,
	LoginEntityId INT FOREIGN KEY REFERENCES LoginEntity(LoginId) ON DELETE SET NULL
);

CREATE TABLE Biznesi (
	 BiznesId INT IDENTITY(1, 1) PRIMARY KEY,
	 Emri VARCHAR(50) NOT NULL,
	 OraHapes TIME,
	 OraMbylljes TIME,
	 LoginEntityId INT FOREIGN KEY REFERENCES LoginEntity(LoginId) ON DELETE SET NULL
);

CREATE TABLE Kategoria (
	--KategoriaId INT IDENTITY(1, 1),
	EmriKategoris VARCHAR(128) PRIMARY KEY
);

CREATE TABLE Produkti (
	ProduktId INT IDENTITY(1, 1) PRIMARY KEY,
	Emri VARCHAR(50) NOT NULL,
	Pershkrimi TEXT,
	Cmimi DECIMAL(18, 2) NOT NULL,
	EmriKategoris VARCHAR(128) FOREIGN KEY REFERENCES Kategoria(EmriKategoris) ON DELETE SET NULL,
	BiznesId INT FOREIGN KEY REFERENCES Biznesi(BiznesId) ON DELETE SET NULL
);

CREATE TABLE Adresa (
	AdresaId INT IDENTITY(1, 1) PRIMARY KEY,
	Qyteti VARCHAR(30) NOT NULL,
	Rruga VARCHAR(50),
	BiznesId INT FOREIGN KEY REFERENCES Biznesi(BiznesId) ON DELETE SET NULL,
	UserId INT FOREIGN KEY REFERENCES Useri(UserId) ON DELETE SET NULL
);

CREATE TABLE Telefoni (
	TelefoniId INT IDENTITY(1, 1) PRIMARY KEY,
	Numri VARCHAR(20) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Useri(UserId) ON DELETE SET NULL,
	BiznesId INT FOREIGN KEY REFERENCES Biznesi(BiznesId) ON DELETE SET NULL,
);

CREATE TABLE Rating (
	--RatingId INT IDENTITY(1, 1),
	Rate INT PRIMARY KEY,
	Meaning TEXT NOT NULL
);

--ALTER TABLE Rating DROP COLUMN RatingId;

CREATE TABLE BusinessFeedback (
    FeedbackId INT IDENTITY(1,1) PRIMARY KEY,
    Subjekti VARCHAR(50) NOT NULL,
    Content TEXT  NOT NULL,
	Rate INT FOREIGN KEY REFERENCES Rating(Rate) ON DELETE SET NULL,
    UserId INT FOREIGN KEY REFERENCES Useri(UserId) ON DELETE SET NULL,
    BiznesId INT FOREIGN KEY REFERENCES Biznesi(BiznesId) ON DELETE SET NULL
);

CREATE TABLE Post (
	PostId INT IDENTITY(1, 1) PRIMARY KEY,
	Title VARCHAR(128) NOT NULL,
	Content TEXT NOT NULL,
	CreateAt DATETIME DEFAULT getdate(),
	BiznesId INT FOREIGN KEY REFERENCES Biznesi(BiznesId) ON DELETE SET NULL
);

CREATE TABLE Comment (
	CommentId INT IDENTITY(1, 1) PRIMARY KEY,
	Content TEXT NOT NULL,
	PostId INT FOREIGN KEY REFERENCES Post(PostId) ON DELETE SET NULL,
	UserId INT FOREIGN KEY REFERENCES Useri(UserId) ON DELETE SET NULL,
	CreateAt DATETIME DEFAULT getdate(),
);

CREATE TABLE SoftwareFeedback (
	FeedbackId INT IDENTITY(1,1) PRIMARY KEY,
    Subjekti VARCHAR(50) NOT NULL,
    Content TEXT  NOT NULL,
	Rate INT FOREIGN KEY REFERENCES Rating(Rate) ON DELETE SET NULL,
    LoginId INT FOREIGN KEY REFERENCES LoginEntity(LoginId) ON DELETE SET NULL,
);

CREATE TABLE Favorite (
	FavoriteId INT IDENTITY(1, 1) PRIMARY KEY,
	UserId INT FOREIGN KEY REFERENCES Useri(UserId) ON DELETE SET NULL,
	BiznesId INT FOREIGN KEY REFERENCES Biznesi(BiznesId) ON DELETE SET NULL
);

CREATE TABLE PostLike (
	PostLikeId INT IDENTITY(1, 1) PRIMARY KEY,
	UserId INT FOREIGN KEY REFERENCES Useri(UserId) ON DELETE SET NULL,
	PostId INT FOREIGN KEY REFERENCES Post(PostId) ON DELETE SET NULL
);

CREATE TABLE Porosia (
	PorosiaId INT IDENTITY(1, 1) PRIMARY KEY,
	CreatedAt DATETIME DEFAULT getdate(),
	UserId INT FOREIGN KEY REFERENCES Useri(UserId) ON DELETE SET NULL,
	BiznesId INT FOREIGN KEY REFERENCES Biznesi(BiznesId) ON DELETE SET NULL
);

CREATE TABLE PorosiaProdukti (
	PorosiaProduktiId INT IDENTITY(1, 1) PRIMARY KEY,
	PorosiaId INT FOREIGN KEY REFERENCES Porosia(PorosiaId) ON DELETE SET NULL,
	ProduktiId INT FOREIGN KEY REFERENCES Produkti(ProduktId) ON DELETE SET NULL
);

CREATE TABLE ReklamaType (
	ReklamaTypeId INT IDENTITY(1, 1),
	Emri VARCHAR(128) PRIMARY KEY,
	CmimiPerDite DECIMAL(18, 2) NOT NULL
);

CREATE TABLE Reklama (
	ReklamaId INT IDENTITY(1, 1) PRIMARY KEY,
	CreateAt DATE DEFAULT getdate(),
	EndsAt DATE,
	ReklamaTypeEmri VARCHAR(128) FOREIGN KEY REFERENCES ReklamaType(Emri) ON DELETE SET NULL,
	BiznesId INT FOREIGN KEY REFERENCES Biznesi(BiznesId) ON DELETE SET NULL
);

CREATE TABLE Search (
	SearchId INT IDENTITY(1, 1) PRIMARY KEY,
	Content TEXT NOT NULL
);

CREATE TABLE Roles (
	RoleId INT IDENTITY(1, 1) PRIMARY KEY,
	Emri VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE LoginsRoles (
	LoginsRolesId INT IDENTITY(1, 1) PRIMARY KEY,
	RoleId INT FOREIGN KEY REFERENCES Roles(RoleId) ON DELETE SET NULL,
	LoginEntityId INT FOREIGN KEY REFERENCES LoginEntity(LoginId) ON DELETE SET NULL
);